name = "aiqbrain-offer-engine"
main = "src/worker.ts"
workers_dev = true

compatibility_date = "2025-08-01"

compatibility_flags = ["nodejs_compat"]

## Note: Wrangler auto-detects tsconfig.json; explicit [build].tsconfig not needed

[observability]
enabled = true

[assets]
directory = "public"
binding = "ASSETS"

# Run on colo(s) closest to where the data is used to reduce cold starts and latency
[placement]
mode = "smart"


[vars]
# NOTE: Do not put CPAGrip/OGAds secrets here — use `wrangler secret` (see bottom).
# Safe non-secret fallbacks (API keys are set via `wrangler secret`)
BASE_URL = "https://aiqbrain-offer-engine.jasonhslaughter.workers.dev"
CORS_ALLOW_ORIGIN = "*"
# Enable all supported networks in production
NETWORKS_ENABLED = "ogads,cpagrip,mylead,maxbounty"
FALLBACK_ANDROID = "https://aiqengage.com/access"
FALLBACK_IOS     = "https://singingfiles.com/show.php?l=0&u=2427730&id=69234&tracking_id="
FALLBACK_GENERIC = "https://aiqengage.com/access"
GREEN_MAX_MINUTES = "7"  # default threshold for 'GREEN' tier (videos ≤7 min)
MYLEAD_API_BASE = "https://api.mylead.eu/api/external/v1/"
MYLEAD_OFFERS_PATH = ""
MYLEAD_API_TOKEN = ""
ADMIN_TOKEN = ""
WEBHOOK_URL = ""

# CPAGrip (non-secret, safe to include in [vars])
CPAGRIP_USER = "YOUR_USER_ID"         # from CPAGrip feed page (numeric)
CPAGRIP_PUBKEY = "YOUR_PUBLIC_KEY"    # safe to ship to client/worker
CPAGRIP_OFFERS_TTL = "900"            # seconds (optional; default 15m)

# KV namespaces (IDs from
#   npx wrangler kv namespace create REGISTRY
#   npx wrangler kv namespace create LOGS
# )
[[kv_namespaces]]
binding = "REGISTRY"
id = "d33cf5ce1d144d8784002ada07c3f69c"

[[kv_namespaces]]
binding = "LOGS"
id = "7c3eb5b4694b46eb88099c6cc443d915"

# Secrets (set these via Wrangler, not here):
#   # CPAGrip private API key (SECRET — do not place in [vars])
#   wrangler secret put CPAGRIP_KEY
#
#   # OGAds (optional, only if "ogads" is enabled in NETWORKS_ENABLED)
#   npx wrangler secret put OGADS_API_KEY
